// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	OrderID    string       `json:"orderID"`
	UserID     string       `json:"userID"`
	Items      []*OrderItem `json:"items"`
	TotalPrice float64      `json:"totalPrice"`
	Status     string       `json:"status"`
	PlacedAt   string       `json:"placedAt"`
}

type OrderInput struct {
	UserID string            `json:"userID"`
	Items  []*OrderItemInput `json:"items"`
}

type OrderItem struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type OrderItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ProductID      string  `json:"productID"`
	Name           string  `json:"name"`
	Price          float64 `json:"price"`
	InventoryCount int     `json:"inventoryCount"`
}

type ProductInput struct {
	Name           string  `json:"name"`
	Price          float64 `json:"price"`
	InventoryCount int     `json:"inventoryCount"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}
